# Generated by Django 3.0.4 on 2020-03-10 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='tags',
            field=models.ManyToManyField(blank=True, null=True, related_name='snippets', to='snippets.Tag'),
        ),
    ]
