# Generated by Django 3.0.4 on 2020-03-10 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_auto_20200310_0520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='The snippet this is forked from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='snippets.Snippet'),
        ),
    ]
