# Generated by Django 3.0.4 on 2020-03-10 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20200310_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(blank=True, help_text='Optional description of the code', null=True),
        ),
    ]
