# Generated by Django 3.0.4 on 2020-03-11 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0005_auto_20200310_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='snippet',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description of the code', null=True),
        ),
        migrations.AlterField(
            model_name='snippet',
            name='code',
            field=models.TextField(default=0, help_text='The code of the snippet'),
            preserve_default=False,
        ),
    ]
